### ISSUE TITLE
Make Tooltips Css/Js

### ISSUE THREAD

**Issue by codearclab** [codearclab/codearc#2]
# Create Tooltips

A tooltip is a short message that appears when a user interacts with a specific element on a website or app. Tooltips are also known as screentips or hover help.

## Positioning Tooltips
By default, the tooltip will appear on top of the element.

Use the data-placement attribute to set the position of the tooltip on top, bottom, left or the right side of the element

***Tip: You can also use the data-placement attribute with a value of "auto", which will let the browser decide the position of the tooltip. For example, if the value is "auto left", the tooltip will display on the left side when possible, otherwise on the right.***

* See bootstrap reference:- https://getbootstrap.com/

> Is this file you will add css code dist/css/blnkoo.css
> In this file you will add js code dist/js/blnkoo.js

**Comment by surajkumar345678** [comment]
Hey @codearclab, i am interested in this issue, can you assign this task to me?
